baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '(â–°Ë˜â—¡Ë˜â–°)'
theme = 'hugo-bearcub'
copyright = "ðŸ”¥"
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[params]
themeStyle = "herman"
dateFormat = "2006-01-02"
madeWith = "2024"
